[tool.poetry]
description = ''
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
jupyterlab = "^4.3.5"
pandas = "^2.2.3"
seaborn = "^0.13.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
